### ISSUE TITLE
Issues with keys for package repositories.

### ISSUE THREAD

**Issue by cjemorton** [lucasteligioridis/raspbernetes#3]
Had to manually go into each pi and pull down the correct signing keys for the package repositories.

**Comment by lucasteligioridis** [comment]
Can you please elaborate on this a little further? I'm confused as to what the issue is.

**Comment by lucasteligioridis** [comment]
Closing due to stale responses. Will re-open when more information has been given.

**Comment by cjemorton** [comment]
Go ahead and close again. - no worries.

I was just mentioning that the keys used to sign the repository were stale - they needed to be updated manually.

So when attempting to bring a whole cluster online - it would hang until the correct signing keys were updated.

Just a quick google search brought up an article talking about what was going on.

Here's an article that talks about this: https://linux-audit.com/how-to-solve-an-expired-key-keyexpired-with-apt/

**Comment by lucasteligioridis** [comment]
Ah nice, appreciate the message. I might fire up a cluster again and get this more "maintainable" this is a good article. Cheers mate!

**Comment by cjemorton** [comment]
No worries. I forgot all about the trouble. My clusters down right now as well. Good luck.
